### ISSUE TITLE
Consulta CSBTIPADDRESS

### ISSUE THREAD

**Issue by fproldan** [TodoPago/SDK-Python#4]
Buenas tardes, necesito desde un sistema ERP enviar un link de pago a un cliente.
El campo CSBTIPADDRESS es obligatorio, pero dado a que el cliente no ingresa al sistema a "comprar" o completar un "carrito" sino que el vendedor envia una solicitud de pago no tengo disponible ese dato.

Como se puede solucionar?

Gracias

**Comment by alejandro021987** [comment]
Que tal @fproldan , como bien decis, para generar el formulario de pago es un campo obligatorio CSBTIPADDRESS como los otros correspondientes a domicilios y estos no pueden omitirse. Por esto, lo que podés hacer es asignarle valores por defecto a esas variables de manera de generar el formulario de pago. Tambien podes generar botones de pago sin necesidad de estos campos desde https://portal.todopago.com.ar/app/#crearBoton . 
Saludos!
