### ISSUE TITLE
<ApplicationIdentification/> not mapped to message part

### ISSUE THREAD

**Issue by lucasmg-dev** [TodoPago/SDK-Python#5]
Tengo implementado el sdk hace ya tiempo y de golpe empezo a darme este error al crear el sendAuthorizeRequest().

`<ApplicationIdentification/> not mapped to message part`

**Comment by alejandro021987** [comment]
Hola @lucasmg-dev , Actualmente está funcionando sin problemas el sdk, que version tenes de python? puede que no haya estado funcionando todopago en ese momento.

**Comment by joae** [comment]
Hola @alejandro021987, tengo el mismo problema haciendo pruebas en test.
Aparentemente eso significa que la respuesta vienen con el tag ApplicationIdentification que no esta en el esquema del servicio SOAP

**Comment by joae** [comment]
@alejandro021987 debbugeando el codigo de la lib, el problema es que envia el campo LANGUAGEVERSION que excede el tamaño permitido.

todopagoconnector.py
`diccionario["LENGUAGEVERSION"]=sys.version`

El sopa retorna el siguiente error:
<api:ResultMessage>ERROR: LENGUAGEVERSION supera largo maximo permitido</api:ResultMessage>'

En mi caso rompe en unix(prod) y mac(local). Donde sys.version es:
'3.6.4 (default, Jan  2 2018, 13:14:21) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]'

**Comment by lucasmg-dev** [comment]
podriamos quitar el salto de linea para `sys.version` y evitariamos el problema.

**Comment by guillermoluced** [comment]
Hola, la siguiente version solucianara el problema, por el momento en el archivo "lib/todopagoconnector.py" modificar la linea "diccionario["LENGUAGEVERSION"]=sys.version" por "diccionario["LENGUAGEVERSION"]=sys.version()"

**Comment by zaoral** [comment]
Buen dia, haciendo los cambios indicados en este hilo me sigue dando error "<ApplicationIdentification/> not mapped to message part" les pasa lo mismo. que novedades tienen sobre este error

**Comment by zaoral** [comment]
> Buen dia, haciendo los cambios indicados en este hilo me sigue dando error " not mapped to message part" les pasa lo mismo. que novedades tienen sobre este error

OJO, hice pruebas en mi local y funciona para python2.7 pero no para paython3.5
