### ISSUE TITLE
Mezcla de Spanish e English en el código

### ISSUE THREAD

**Issue by gusarg81** [TodoPago/SDK-Python#8]
Es una "mala costumbre" para desarrolladores del habla Hispana mezclar tipos/variables/constantes/etc de Español e Inglés.

Sería bueno que mejoran esto para que el código sea un poco más legible y limpio, usando únicamente inglés, dado que todo framework y lenguaje de programación está "interpretado" con este Idioma.

**Comment by curcio79** [comment]
@gusarg81 gracias por el comentario y tenes razon en lo que decis. Estamos trabajando en mejorarlo y corregir esas cosas. Gracias por todo.
