### ISSUE TITLE
Exception Value: (307, 'Temporary Redirect')

### ISSUE THREAD

**Issue by aguterrestre** [TodoPago/SDK-Python#9]
Al usar response = tpc.sendAuthorizeRequest(optionsSAR_comercio, optionsSAR_operacion) se genera una excepción que se visualiza en el navegador: Exception Location: c:\Django\env\Lib\site-packages\suds\Client.py, line 677, in process_reply.
Esa linea se refiere a raise Exception((status, description)).

![307 Temporary Redirect](https://user-images.githubusercontent.com/69941951/120393467-56e5fd80-c308-11eb-88c9-b84c33644248.jpg)

**Comment by curcio79** [comment]
@aguterrestre buenas tardes, probaste con uno de los ejemplos del sdk? asi vemos la respuesta

**Comment by aguterrestre** [comment]
No probé con el ejemplo. Ahora lo voy a hacer y les comento la respuesta.
Adjunto el error que da actualmente en el comentario anterior.

**Comment by curcio79** [comment]
@aguterrestre buenos dias, pudiste hacer la prueba?

**Comment by aguterrestre** [comment]
Buenas tardes. Pude hacer pruebas con el ejemplo_completo. Paso a comentarte los resultados.
Cuando intento logearme con las credenciales de todo pago en modo test recibo error de la contraseña es incorrecta. Si lo hago en modo produccion no tengo problemas.
Al momento de hacer un pago, cargo datos de prueba (obtenidos de https://developers.todopago.com.ar/site/datos-de-prueba) y al aceptar me redirige a URL_ERROR. Intenté con las dos tarjetas de prueba que hay. También intenté generar SAR y termina sucediendo lo mismo, redirige a URL_ERROR.

**Comment by curcio79** [comment]
@aguterrestre buenos dias, genial q pasamos ya el error anterior, lo q te pido es q me pases la respuesta del log asi analizamos el porq te redirige a esa URL, verificaste todos los campos enviados?

**Comment by aguterrestre** [comment]
Buenos días! ¿Desde donde puedo consultar el log? Los campos que uso son los del ejemplo_completo, es decir, no introduje ningún dato distinto a como esta el ejemplo.

**Comment by curcio79** [comment]
@aguterrestre en la respuesta TP te responde el motivo del error (sea de la cuenta o el formulario), seguramente algun campo no fue validado correctamente. Captura eso y pasalo, ahi debe estar el motivo

**Comment by aguterrestre** [comment]
Adjunto imagen del log al hacer login en modo test.
![log login modo test](https://user-images.githubusercontent.com/69941951/122205920-2ad58b00-ce77-11eb-9b15-1beac342dd4c.png)

Adjunto imagen del log al realizar el pago.
![log al hacer el pago](https://user-images.githubusercontent.com/69941951/122206064-56587580-ce77-11eb-97b7-72fd3c17735e.png)

**Comment by curcio79** [comment]
@aguterrestre buenos dias, ahi veo 2 problemas diferentes, el log del test, lo hiciste con http me parece, es correcto? Si es asi, proba con https. Con relacion al log de pago tenes bloqueado el usuario por intentos incorrectos, ahi tambien necesitas https. Vas a necesitar desbloquearlo desde la web para seguir continuando con las pruebas. Saludos

**Comment by aguterrestre** [comment]
Buenos días. Muchas gracias por la ayuda.
Estoy probando con localhost desde mi pc. ¿Que me recomendas?

**Comment by curcio79** [comment]
@aguterrestre podrias instalarte un certificado autofirmado o usar directamente produccion. Acordate de desbloquear tu usuario. Saludos

**Comment by curcio79** [comment]
@aguterrestre pudiste avanzar? sino cierro el ticket y genera uno nuevo con el nuevo problema. Saludos

**Comment by aguterrestre** [comment]
Buenas noches! Seguimos trabajando en la integración. Tus comentarios fueron de ayuda. Te aviso apenas tenga novedades.

**Comment by curcio79** [comment]
@aguterrestre me alegro, cualquier cosa crea un nuevo ticket. Saludos
